### ISSUE TITLE
Console内嵌 - 点击查看视频能否显示全屏

### ISSUE THREAD

**Issue by leahchen123** [yunify/qingcloud-docs#128]
点击查看视频能否显示全屏，现在的只是在内嵌内容里面浮层，查看图二

![image](https://user-images.githubusercontent.com/41466916/101447131-933f2f00-395f-11eb-9d86-3d780d763f25.png)
![image](https://user-images.githubusercontent.com/41466916/101447348-021c8800-3960-11eb-990d-e969e7ca705a.png)

**Comment by sunshine12cc** [comment]
视频  我只能控制内嵌的那一块儿  如果要在你们的console里全屏的话 我这儿应该做不了。
