### ISSUE TITLE
紧急 - 面包屑包含了没有内容的分类，console内嵌+文档中心均有这个问题

### ISSUE THREAD

**Issue by leahchen123** [yunify/qingcloud-docs#130]
面包屑包含了没有内容的分类，这个是不是不太合理？一般没有内容最好是不能点击，不然就是空白一片
![image](https://user-images.githubusercontent.com/41466916/101470358-dbbb1480-3980-11eb-96b2-c0f5602b69a1.png)

**Comment by leahchen123** [comment]
![image](https://user-images.githubusercontent.com/41466916/101470663-3c4a5180-3981-11eb-87c7-9bfec13b8255.png)

**Comment by sunshine12cc** [comment]
每个index页  可以加上_build:
    render: false   这个参数   这样就不会有跳转到空白index   效果与KubeSphere  面包屑一致
