### ISSUE TITLE
紧急 - 文档中心 - 如果文档没有开发类型的文档，这个模块需要隐藏。当前不合理

### ISSUE THREAD

**Issue by leahchen123** [yunify/qingcloud-docs#135]
如果文档没有开发类型的文档，这个模块需要隐藏。当前不合理
![image](https://user-images.githubusercontent.com/41466916/101612552-bcd28600-3a45-11eb-948c-1de5ed648f60.png)

**Comment by sunshine12cc** [comment]
这个需要相应的产品  填充文档  目前确实还存在缺失
