### ISSUE TITLE
目录字体大小和位置不协调

### ISSUE THREAD

**Issue by ephen** [yunify/qingcloud-docs#15]
![image](https://user-images.githubusercontent.com/12691823/96573697-1ac5d580-1301-11eb-968e-f9d82b3a8b44.png)

**Comment by FeynmanZhou** [comment]
@ephen  这个可以在前端样式调整。另外，我在最新的 master 分支代码里做了一点调整，产品动态也以目录的形式展示会不会更好？

![image](https://user-images.githubusercontent.com/40452856/96575259-1e5a5c00-1303-11eb-99d8-68d31aa9f95e.png)

**Comment by ephen** [comment]
> @ephen 这个可以在前端样式调整。另外，我在最新的 master 分支代码里做了一点调整，产品动态也以目录的形式展示会不会更好？
> 
> ![image](https://user-images.githubusercontent.com/40452856/96575259-1e5a5c00-1303-11eb-99d8-68d31aa9f95e.png)

放目录感觉不太好，如果没有其他的相关公告，产品动态就是最吸睛的内容，在首屏挺好的，有冲击力一些。

**Comment by sunshine12cc** [comment]
调整了单独产品动态目录的 字体大小和位置
