### ISSUE TITLE
有些图片因截图区域比较大而看不清，建议提供查看原图或放大的操作

### ISSUE THREAD

**Issue by ephen** [yunify/qingcloud-docs#16]
![image](https://user-images.githubusercontent.com/12691823/96573998-785a2200-1301-11eb-82c2-3d975b140833.png)

**Comment by FeynmanZhou** [comment]
@ephen BTW，看截图左侧目录，好像跟最新的代码有一点滞后

**Comment by sunshine12cc** [comment]
已增加此功能
