### ISSUE TITLE
代码块的样式不统一，有的也看不太清，是否可以调整下？

### ISSUE THREAD

**Issue by ephen** [yunify/qingcloud-docs#17]
![image](https://user-images.githubusercontent.com/12691823/96574496-1cdc6400-1302-11eb-8bf7-45402097fd78.png)
![image](https://user-images.githubusercontent.com/12691823/96574548-2e257080-1302-11eb-9704-de2e1dc97d99.png)

**Comment by sunshine12cc** [comment]
fixed
