### ISSUE TITLE
点击下载用户文档 pdf ，报 404 错误且无法生成文件

### ISSUE THREAD

**Issue by ephen** [yunify/qingcloud-docs#18]
![image](https://user-images.githubusercontent.com/12691823/96574818-865c7280-1302-11eb-8935-1c053fdef8af.png)
![image](https://user-images.githubusercontent.com/12691823/96574859-91af9e00-1302-11eb-8c6d-90662b4ad89e.png)

**Comment by FeynmanZhou** [comment]
下载 PDF 会在内容基本完善后支持

**Comment by sunshine12cc** [comment]
pdf下载已支持 但是由于该功能需要安装额外依赖  所以只能在线上使用  本地预览不支持pdf下载
