### ISSUE TITLE
[Console嵌入] 鼠标拖动到比较宽的时候左侧的目录树样式跟设计稿有误差，需要对比下

### ISSUE THREAD

**Issue by leahchen123** [yunify/qingcloud-docs#19]
鼠标拖动到比较宽的时候左侧的目录树样式跟设计稿有误差，需要对比下
![image](https://user-images.githubusercontent.com/41466916/96576466-ce7c9480-1304-11eb-82d4-ae3eb4c440e2.png)

**Comment by sunshine12cc** [comment]
fixed
