### ISSUE TITLE
产品动态 Content 不支持文内换行和链接

### ISSUE THREAD

**Issue by ephen** [yunify/qingcloud-docs#22]
![image](https://user-images.githubusercontent.com/12691823/97284923-96cd9980-187c-11eb-9091-67a848095765.png)

**Comment by ephen** [comment]
另外，有些单纯公告不适合配文档，URL 是否可以支持可选？
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by FeynmanZhou** [comment]
@sunshine12cc 应该要支持 URL 可选，没有加 URL 字段就不展示

**Comment by sunshine12cc** [comment]
fixed
