### ISSUE TITLE
给文档配置 Netlify 支持在页面预览 PR

### ISSUE THREAD

**Issue by FeynmanZhou** [yunify/qingcloud-docs#30]
Netlify: https://www.netlify.com/

预期效果：希望在 PR 提交后在 PR 中生成一个预览链接，点击 preview 即可一键跳转到前端界面查看最终效果。

![image](https://user-images.githubusercontent.com/40452856/97852986-7432f900-1d32-11eb-85a5-c6e81f97372e.png)

示例 PR：https://github.com/kubesphere/website/pull/437

**Comment by sunshine12cc** [comment]
已安装此功能
