### ISSUE TITLE
首页小卡片上只能添加五个子模块，第六个没有显示

### ISSUE THREAD

**Issue by tcchend** [yunify/qingcloud-docs#32]
我们这里CloudSat有六个子模块，如下
![image](https://user-images.githubusercontent.com/34952554/98088266-33ff8200-1ebc-11eb-98f4-5f9b79aa5c87.png)

在项目 qingcloud/content/ 目录编辑内容，相应的加了六个子栏目，首页小卡片只展示了其中五个，展示顺序也不一致
![image](https://user-images.githubusercontent.com/34952554/98088159-16cab380-1ebc-11eb-8f55-418409b8888b.png)

**Comment by sunshine12cc** [comment]
放开了此限制
