### ISSUE TITLE
小卡片下面子菜单顺序不可以按照页面排布顺序进行排列

### ISSUE THREAD

**Issue by tcchend** [yunify/qingcloud-docs#34]
小卡片中菜单顺序如下
![image](https://user-images.githubusercontent.com/34952554/98192701-77a6ca00-1f56-11eb-880d-57b5530da23a.png)
实际页面顺序如下
![image](https://user-images.githubusercontent.com/34952554/98192549-30203e00-1f56-11eb-9ff9-2cac34232704.png)

可不可以让用户自己调整顺序保持一致

**Comment by sunshine12cc** [comment]
此功能目前已经具备  只需要调整相应index配置处的weight 就可以了
