### ISSUE TITLE
content/category.json 替换为 toml 或 yaml

### ISSUE THREAD

**Issue by Xuanwo** [yunify/qingcloud-docs#43]
`category.json` 格式复杂而且无法显示 utf8 字符，编辑起来不方便，容易出错，是否可以换成 toml 或者 yaml 等形式

**Comment by Xuanwo** [comment]
![image](https://user-images.githubusercontent.com/5351546/99373836-d9731680-28fc-11eb-998e-ac9f567a1aee.png)

能写代码解决的问题就不要让维护者手动编辑

**Comment by sunshine12cc** [comment]
麻烦拉取最新的代码 这个文件在9月17日的改版中已去除

**Comment by Xuanwo** [comment]
OK, #40 把这个文件加回来了，可以提个 PR 再删掉

**Comment by sunshine12cc** [comment]
#40  这次提交还删除了2个系统文件  我也会加回来

**Comment by Xuanwo** [comment]
问题解决之后再 close issue，可以在对应的 PR 里面引用这个 issue，PR merge 之后会自动关闭
