### ISSUE TITLE
前端问题记录

### ISSUE THREAD

**Issue by FeynmanZhou** [yunify/qingcloud-docs#6]
- [x] 1. 目录不应该展示父目录，仅保留红圈部分
![image](https://user-images.githubusercontent.com/40452856/95567341-64870400-0a55-11eb-9171-29af26dce417.png)

- [x] 2. 左上角的面包屑最左侧应该回到首页
![image](https://user-images.githubusercontent.com/40452856/95567384-71a3f300-0a55-11eb-9c12-a1e11181d20a.png)

- [x] 3. 视频改成手动播放
![image](https://user-images.githubusercontent.com/40452856/95567493-97c99300-0a55-11eb-911b-0e04d709f968.png)

- [x] 4. 每篇 .md 应支持自定义 `keyword`

**Comment by FeynmanZhou** [comment]
问题1中的 `test1` 也无需展示，左侧的目录树只用展示 `test1` 目录下的所有子目录
![image](https://user-images.githubusercontent.com/40452856/95681073-6812ba80-0c10-11eb-8950-69b25cfc4559.png)

**Comment by roughhlz** [comment]
下拉框样式和设计稿还原一下：https://zpl.io/aBJNW5k
![17921602669198_ pic](https://user-images.githubusercontent.com/72846137/95973394-2d926300-0e46-11eb-881f-a4a760320d8c.jpg)

**Comment by roughhlz** [comment]
搜索内容顶部缺少底色，缺少返回按钮
![17941602670022_ pic_hd](https://user-images.githubusercontent.com/72846137/95975142-60d5f180-0e48-11eb-8aa0-7873f7ee67e9.jpg)
![17951602670298_ pic](https://user-images.githubusercontent.com/72846137/95975435-c0340180-0e48-11eb-94b5-702504bd5b01.jpg)

**Comment by roughhlz** [comment]
修改下banner 标题与文案间距，文案字重
![17931602669682_ pic_hd](https://user-images.githubusercontent.com/72846137/95977391-6ed94180-0e4b-11eb-9932-a3d7286dcfd4.jpg)

**Comment by roughhlz** [comment]
修改断行标题间距
![17961602671412_ pic_hd](https://user-images.githubusercontent.com/72846137/95977577-9defb300-0e4b-11eb-8d23-c3e77c62fa72.jpg)
![Uploading 截屏2020-10-14 下午6.33.27.png…]()

**Comment by sunshine12cc** [comment]
fixed

**Comment by sunshine12cc** [comment]
> * [x]  1. 目录不应该展示父目录，仅保留红圈部分
>   ![image](https://user-images.githubusercontent.com/40452856/95567341-64870400-0a55-11eb-9171-29af26dce417.png)
> * [x]  2. 左上角的面包屑最左侧应该回到首页
>   ![image](https://user-images.githubusercontent.com/40452856/95567384-71a3f300-0a55-11eb-9c12-a1e11181d20a.png)
> * [x]  3. 视频改成手动播放
>   ![image](https://user-images.githubusercontent.com/40452856/95567493-97c99300-0a55-11eb-911b-0e04d709f968.png)
> * [x]  4. 每篇 .md 应支持自定义 `keyword`


fixed

**Comment by sunshine12cc** [comment]
fixed
